"""Create orders

Revision ID: ebafc7b5d51c
Revises: 7c869a7e9bb6
Create Date: 2024-09-29 11:05:02.910041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebafc7b5d51c'
down_revision: Union[str, None] = '7c869a7e9bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SENT', 'DELIVERED', name='orderstatus'), nullable=False),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('order_items',
    sa.Column('product_uuid', sa.Uuid(), nullable=False),
    sa.Column('order_uuid', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_uuid'], ['orders.pk'], ),
    sa.ForeignKeyConstraint(['product_uuid'], ['products.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
